I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 137, in script
    $ picture = gimar
  File "game/script.rpy", line 137, in <module>
    $ picture = gimar
NameError: name 'gimar' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 137, in script
    $ picture = gimar
  File "D:\Renpy\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Renpy\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 137, in <module>
    $ picture = gimar
NameError: name 'gimar' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
Nibelungen 1.0
Wed Apr 01 13:25:44 2020
